# CI for Product Catalog Service
name: Recocamentadtion services

on: 
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Setup Python 3.12
          uses: actions/setup-python@v4
          
          with:
            python-version: 3.12 

        
        # - name: Build
        #   run: |
        #     cd src/recommendation
        #     go mod download
        #     go build -o product-catalog-service main.go

      #  - name: Install dependencies
      #    run: |
      #       python -m pip install --upgrade pip  # ✅ Upgrade pip
      #       python -m pip install pytest  # ✅ Install pytest correctly


      #   - name: Run unit tests
      #     run: |
      #       cd src/recommendation
      #       pytest

    
    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4
        
        - name: Setup Python 3.12
          uses: actions/setup-python@v4
          with:
           python-version: 3.12
        
        # - name: Run golangci-lint
        #   uses: golangci/golangci-lint-action@v6
        #   with:
        #     version: v1.55.2
        #     run: golangci-lint run
        #     working-directory: src/product-catalog

    docker:
        runs-on: ubuntu-latest

        needs: build

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: Install Docker
          uses: docker/setup-buildx-action@v1
        
        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Docker Push
          uses: docker/build-push-action@v6
          with:
            context: src/recommendation
            file: src/recommendation/Dockerfile
            push: true
            
            tags: ${{ secrets.DOCKER_USERNAME }}/recommendation:${{github.run_id}}

    
    updatek8s:
        runs-on: ubuntu-latest

        needs: docker

        steps:
        - name: checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}

        - name: Update tag in kubernetes deployment manifest
          run: | 
               sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/recommendation:${{github.run_id}}|" kubernetes/recommendation/deploy.yaml
        
        

        


        - name: Commit and push changes
          run: |
            git config --global user.email "vamsisai523114@gmail.com"
            git config --global user.name "Vs7sai"
            git add kubernetes/recommendation/deploy.yaml
            git commit -m "[CI]: update the recomendationtag"
            git push origin HEAD:main -f

        
        
          


        